// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);

// Temperature
lv_obj_t *tempArc; // The temperature arc object
lv_obj_t *tempValueLabelInt; // Label for the integer part of the temperature
lv_obj_t *tempValueLabelDecimal; // Label for the decimal part of the temperature
void init_temperature_display(lv_obj_t *parent);

// Humidity
lv_obj_t *humidity_arc;
lv_obj_t *humidity_value_label;
void init_humidity_display(lv_obj_t *parent);

lv_obj_t * ui_scrMain;
lv_obj_t * ui_pnlMain;
lv_obj_t * ui_lblMilliseconds;
lv_obj_t * ui_lblMillisecondsValue;
lv_obj_t * ui_lblCdr;
lv_obj_t * ui_lblCdrValue;

lv_obj_t * ui_AhtTemp;
lv_obj_t * ui_AhtTempValue;

lv_obj_t * ui_AhtHum;
lv_obj_t * ui_AhtHumValue;

lv_obj_t * ui_BmpTemp;
lv_obj_t * ui_BmpTempValue;

lv_obj_t * ui_BmpPress;
lv_obj_t * ui_BmpPressValue;

void ui_event_Rotate(lv_event_t * e);
lv_obj_t * ui_Rotate;
lv_obj_t * ui_Label1;
void ui_event_btnCount(lv_event_t * e);
lv_obj_t * ui_btnCount;
lv_obj_t * ui_lblButton;
lv_obj_t * ui_lblCount;
lv_obj_t * ui_lblCountValue;
lv_obj_t * ui_Image1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_lenax[1] = {&ui_img_lena80x80_png};

extern float br_level;
lv_obj_t *time_label;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Rotate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnRotateClicked(e);
    }
}
void ui_event_btnCount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    // lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnAddOneClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrMain);
}
