// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);

// Temperature
lv_obj_t *tempArc; // The temperature arc object
lv_obj_t *tempValueLabelInt; // Label for the integer part of the temperature
lv_obj_t *tempValueLabelDecimal; // Label for the decimal part of the temperature
void init_temperature_display(lv_obj_t *parent);

// Humidity
lv_obj_t *humidity_arc;
lv_obj_t *humidity_value_label;
void init_humidity_display(lv_obj_t *parent);

extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_pnlMain;
extern lv_obj_t * ui_lblMilliseconds;
extern lv_obj_t * ui_lblMillisecondsValue;
extern lv_obj_t * ui_lblCdr;
extern lv_obj_t * ui_lblCdrValue;

extern lv_obj_t * ui_AhtTemp;
extern lv_obj_t * ui_AhtTempValue;

extern lv_obj_t * ui_AhtHum;
extern lv_obj_t * ui_AhtHumValue;

extern lv_obj_t * ui_BmpTemp;
extern lv_obj_t * ui_BmpTempValue;

extern lv_obj_t * ui_BmpPress;
extern lv_obj_t * ui_BmpPressValue;

void ui_event_Rotate(lv_event_t * e);
extern lv_obj_t * ui_Rotate;
extern lv_obj_t * ui_Label1;

void ui_event_btnCount(lv_event_t * e);
extern lv_obj_t * ui_btnCount;
extern lv_obj_t * ui_lblButton;
extern lv_obj_t * ui_lblCount;
extern lv_obj_t * ui_lblCountValue;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;

extern float br_level;
extern void smartdisplay_lcd_set_backlight(float duty);

LV_IMG_DECLARE(ui_img_lena80x80_png);    // assets/Lena80x80.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
