// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include <stdio.h>
#include "../ui.h"
// #include "../components/lv_img_temp_icon.h" 

void init_temperature_display(lv_obj_t *parent) {
    // lv_obj_t *ui_tempContainer = lv_obj_create(ui_tempContainer);
    // lv_obj_set_size(tempArc, 140, 140);

    // Create the temperature arc
    tempArc = lv_arc_create(parent);
    lv_arc_set_range(tempArc, 0, 50); // Temperature range from 0 to 50
    lv_obj_set_size(tempArc, 140, 140); // Example size, adjust as needed
    lv_obj_align(tempArc, LV_ALIGN_TOP_LEFT, 0, 0); // Center the arc
    lv_obj_clear_flag(tempArc, LV_OBJ_FLAG_CLICKABLE); // Correct approach to make the arc not react to clicks

    // // Create the temperature icon
    // lv_obj_t *tempIcon = lv_img_create(parent);
    // lv_img_set_src(tempIcon, &lv_img_temp_icon); // Set the source of the image to your converted icon
    // // lv_obj_align(tempIcon, LV_ALIGN_TOP_MID, 0, 10); // Position the icon above the temperature number, adjust as needed
    // lv_obj_align_to(tempIcon, tempArc, LV_ALIGN_OUT_TOP_MID, 0, 50);

    lv_obj_t *temp_label = lv_label_create(parent);
    lv_label_set_text(temp_label, "TEMP");

    // Set the font to lv_font_montserrat_14
    lv_obj_set_style_text_font(temp_label, &lv_font_montserrat_14, 0);

    // Set the text color to yellow
    lv_obj_set_style_text_color(temp_label, lv_color_make(0xFF, 0xFF, 0x00), 0);

    // Position the label above the temperature value
    // Adjust the x and y coordinates as needed
    lv_obj_align_to(temp_label, tempArc, LV_ALIGN_OUT_TOP_MID, 0, 50);    

    // Create the integer part label
    tempValueLabelInt = lv_label_create(parent);
    lv_obj_align_to(tempValueLabelInt, tempArc, LV_ALIGN_CENTER, -20, -10); // Adjust position as needed

    // Create the decimal part label
    tempValueLabelDecimal = lv_label_create(parent);
    lv_obj_align_to(tempValueLabelDecimal, tempValueLabelInt, LV_ALIGN_OUT_RIGHT_BOTTOM, 25, 30); // Right of the integer part

    lv_label_set_text(tempValueLabelInt, "--");
    lv_label_set_text(tempValueLabelDecimal, "-");


    // Example: Apply different styles (e.g., font sizes) to the labels
    static lv_style_t style_int;
    lv_style_init(&style_int);
    lv_style_set_text_font(&style_int, &lv_font_montserrat_46); // Larger font for integer part

    static lv_style_t style_decimal;
    lv_style_init(&style_decimal);
    lv_style_set_text_font(&style_decimal, &lv_font_montserrat_14); // Smaller font for decimal part

    lv_obj_add_style(tempValueLabelInt, &style_int, 0);
    lv_obj_add_style(tempValueLabelDecimal, &style_decimal, 0);
}


void init_humidity_display(lv_obj_t *parent) {
    humidity_arc = lv_arc_create(parent);
    lv_arc_set_range(humidity_arc, 0, 100); // Temperature range from 0 to 50
    lv_arc_set_value(humidity_arc, 0);
    lv_obj_set_size(humidity_arc, 110, 110); // Example size, adjust as needed
    lv_obj_align(humidity_arc, LV_ALIGN_BOTTOM_RIGHT, 0, 0); // Center the arc
    lv_obj_clear_flag(humidity_arc, LV_OBJ_FLAG_CLICKABLE); // Correct approach to make the arc not react to clicks

    lv_obj_t *temp_label = lv_label_create(parent);
    lv_label_set_text(temp_label, "HUM");

    // Set the font to lv_font_montserrat_14
    lv_obj_set_style_text_font(temp_label, &lv_font_montserrat_14, 0);

    // Set the text color to yellow
    lv_obj_set_style_text_color(temp_label, lv_color_make(0xFF, 0xFF, 0x00), 0);

    // Position the label above the temperature value
    // Adjust the x and y coordinates as needed
    lv_obj_align_to(temp_label, humidity_arc, LV_ALIGN_OUT_TOP_MID, 0, 50);    

    // Create the integer part label
    humidity_value_label = lv_label_create(parent);
    lv_obj_align_to(humidity_value_label, humidity_arc, LV_ALIGN_CENTER, -10, 5); // Adjust position as needed

    // Create the decimal part label
    lv_label_set_text(humidity_value_label, "--");


    // Example: Apply different styles (e.g., font sizes) to the labels
    static lv_style_t style_int;
    lv_style_init(&style_int);
    lv_style_set_text_font(&style_int, &lv_font_montserrat_28); // Larger font for integer part

    lv_obj_add_style(humidity_value_label, &style_int, 0);



    // Create the arc for humidity
    // lv_obj_t *humidity_arc = lv_arc_create(parent);
    // lv_arc_set_range(humidity_arc, 0, 100); // Temperature range from 0 to 50
    // lv_arc_set_value(humidity_arc, 0);
    // lv_obj_set_size(humidity_arc, 110, 110);
    // lv_obj_align(humidity_arc, LV_ALIGN_BOTTOM_RIGHT, 0, 0); // Position at bottom right
    // lv_obj_clear_flag(humidity_arc, LV_OBJ_FLAG_CLICKABLE); // Correct approach to make the arc not react to clicks

    // // Create the label for the humidity value
    // lv_obj_t *humidity_value_label = lv_label_create(parent);
    // lv_obj_set_style_text_font(humidity_value_label, &lv_font_montserrat_28, 0); // Use font size 36
    // lv_obj_align_to(humidity_value_label, humidity_arc, LV_ALIGN_BOTTOM_MID, 0, -30); // Center on the arc, adjust y offset as needed

    // lv_label_set_text(humidity_value_label, "--"); // Example value, adjust as needed


    // Create the label for "HUMIDITY"
    // lv_obj_t *humidity_label = lv_label_create(parent);
    // lv_label_set_text(humidity_label, "HUM");
    // lv_obj_set_style_text_font(humidity_label, &lv_font_montserrat_14, 0); // Use font size 14
    // lv_obj_align_to(humidity_label, humidity_arc, LV_ALIGN_OUT_TOP_MID, 0, 45); // Position below the arc

    // static lv_style_t style_humidity_label;
    // lv_style_init(&style_humidity_label);

    // // Set the text color of the style to blue
    // lv_style_set_text_color(&style_humidity_label, lv_color_hex(0x0000FF)); // Hex code for blue

    // // Apply the style to the humidity_label
    // lv_obj_add_style(humidity_label, &style_humidity_label, 0);
}

// Adjusted br_level Update Function for float values
static void update_br_level_display(lv_obj_t *label, float br_level_v) {
    char br_level_str[10]; // Buffer for br_level percentage text
    // snprintf(br_level_str, sizeof(br_level_str), "%.1f%%", br_level_v * 100);
    // snprintf(br_level_str, sizeof(br_level_str), "%d%%", (int)(br_level_v * 100));
    snprintf(br_level_str, sizeof(br_level_str), "%.0f%%", br_level_v * 100);
    lv_label_set_text(label, br_level_str); // Update the label with the new br_level value
    smartdisplay_lcd_set_backlight(br_level_v);
}

// Callback for the increase button
static void increase_br_level_cb(lv_event_t *e) {
    // static float br_level = 0.5; // Starting br_level level, adjust as needed
    br_level += 0.05; // Increase br_level by 10%
    if (br_level > 1) br_level = 1; // Cap br_level at 1
    update_br_level_display(lv_event_get_user_data(e), br_level);
}

// Callback for the decrease button
static void decrease_br_level_cb(lv_event_t *e) {
    br_level -= 0.05; // Decrease br_level by 10%
    if (br_level < 0.05) br_level = 0.05; // Ensure br_level doesn't go below 0.1
    update_br_level_display(lv_event_get_user_data(e), br_level);
}

// Adjusted init_br_level_control function to use float values
void init_br_level_control(lv_obj_t *parent) {
    // Create a label for displaying br_level percentage
    lv_obj_t *br_parent = lv_obj_create(parent); // Create parent object on the active screen

    // Step 3: Optionally set properties of the parent object, like size, position, etc.
    lv_obj_set_size(br_parent, LV_PCT(50), LV_PCT(30)); // Example: Set size to fill the screen
    lv_obj_align(br_parent, LV_ALIGN_BOTTOM_LEFT, 0, 0); // Example: Center the parent object

    lv_obj_t *br_level_label = lv_label_create(br_parent);
    char br_level_str[10];
    // snprintf(br_level_str, sizeof(br_level_str), "%d%%", (int)(br_level * 100));
    snprintf(br_level_str, sizeof(br_level_str), "%.0f%%", br_level * 100);
    lv_label_set_text(br_level_label, br_level_str);
    lv_obj_align(br_level_label, LV_ALIGN_CENTER, 0, 0); // Position the label

    // Create increase button
    lv_obj_t *btn_increase = lv_btn_create(br_parent);
    lv_obj_set_size(btn_increase, 30, 30); // Set button size
    lv_obj_align(btn_increase, LV_ALIGN_CENTER, 40, 0); // Position to the right of the label
    lv_obj_t *label_increase = lv_label_create(btn_increase);
    lv_label_set_text(label_increase, "+");
    lv_obj_center(label_increase);
    lv_obj_add_event_cb(btn_increase, increase_br_level_cb, LV_EVENT_CLICKED, br_level_label);

    // Create decrease button
    lv_obj_t *btn_decrease = lv_btn_create(br_parent);
    lv_obj_set_size(btn_decrease, 30, 30); // Set button size
    lv_obj_align(btn_decrease, LV_ALIGN_CENTER, -40, 0); // Position to the left of the label
    lv_obj_t *label_decrease = lv_label_create(btn_decrease);
    lv_label_set_text(label_decrease, "-");
    lv_obj_center(label_decrease);
    lv_obj_add_event_cb(btn_decrease, decrease_br_level_cb, LV_EVENT_CLICKED, br_level_label);
}


void ui_scrMain_screen_init(void)
{

    static lv_style_t style;
    lv_style_init(&style);

    // Remove padding
    lv_style_set_pad_top(&style, 1);
    lv_style_set_pad_bottom(&style, 1);
    lv_style_set_pad_left(&style, 1);
    lv_style_set_pad_right(&style, 1);

    ui_scrMain = lv_obj_create(NULL);
    lv_obj_add_style(ui_scrMain, &style, 0);
    lv_obj_clear_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlMain = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_pnlMain, lv_pct(100));
    lv_obj_set_height(ui_pnlMain, lv_pct(100));
    lv_obj_set_align(ui_pnlMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pnlMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_lblMilliseconds = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_lblMilliseconds, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_lblMilliseconds, LV_SIZE_CONTENT);    /// 1
    // lv_label_set_text(ui_lblMilliseconds, "Brigtness:\n");

    // ui_lblMillisecondsValue = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_lblMillisecondsValue, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_lblMillisecondsValue, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_lblMillisecondsValue, LV_ALIGN_TOP_RIGHT);
    // lv_label_set_text(ui_lblMillisecondsValue, "--");


    init_temperature_display(ui_pnlMain);
    init_humidity_display(ui_pnlMain);
    init_br_level_control(ui_pnlMain);


    // ui_AhtTemp = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_AhtTemp, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_AhtTemp, LV_SIZE_CONTENT);
    // lv_obj_set_y(ui_AhtTemp, 20);
    // lv_label_set_text(ui_AhtTemp, "AHT Temp:");

    // ui_AhtTempValue = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_AhtTempValue, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_AhtTempValue, LV_SIZE_CONTENT);
    // lv_obj_set_align(ui_AhtTempValue, LV_ALIGN_TOP_RIGHT);
    // lv_obj_set_y(ui_AhtTempValue, 20);
    // lv_label_set_text(ui_AhtTempValue, "--");

    // ui_AhtHum = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_AhtHum, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_AhtHum, LV_SIZE_CONTENT);
    // lv_obj_set_y(ui_AhtHum, 40);
    // lv_label_set_text(ui_AhtHum, "AHT Hum:");

    // ui_AhtHumValue = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_AhtHumValue, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_AhtHumValue, LV_SIZE_CONTENT);
    // lv_obj_set_align(ui_AhtHumValue, LV_ALIGN_TOP_RIGHT);
    // lv_obj_set_y(ui_AhtHumValue, 40);
    // lv_label_set_text(ui_AhtHumValue, "--");

    // ui_BmpTemp = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_BmpTemp, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_BmpTemp, LV_SIZE_CONTENT);
    // lv_obj_set_y(ui_BmpTemp, 60);
    // lv_label_set_text(ui_BmpTemp, "BMP Temp:");

    // ui_BmpTempValue = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_BmpTempValue, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_BmpTempValue, LV_SIZE_CONTENT);
    // lv_obj_set_align(ui_BmpTempValue, LV_ALIGN_TOP_RIGHT);
    // lv_obj_set_y(ui_BmpTempValue, 60);
    // lv_label_set_text(ui_BmpTempValue, "--");

    // ui_BmpPress = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_BmpPress, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_BmpPress, LV_SIZE_CONTENT);
    // lv_obj_set_y(ui_BmpPress, 80);
    // lv_label_set_text(ui_BmpPress, "AHT Pressure:");

    // ui_BmpPressValue = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_BmpPressValue, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_BmpPressValue, LV_SIZE_CONTENT);
    // lv_obj_set_align(ui_BmpPressValue, LV_ALIGN_TOP_RIGHT);
    // lv_obj_set_y(ui_BmpPressValue, 80);
    // lv_label_set_text(ui_BmpPressValue, "--");

    // ui_lblCdr = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_lblCdr, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_lblCdr, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_lblCdr, 0);
    // lv_obj_set_y(ui_lblCdr, 100);
    // lv_label_set_text(ui_lblCdr, "Light:");

    ui_lblCdrValue = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblCdrValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCdrValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCdrValue, 0);
    lv_obj_set_y(ui_lblCdrValue, 200);
    lv_obj_set_align(ui_lblCdrValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblCdrValue, "--");

    ui_Rotate = lv_btn_create(ui_pnlMain);
    lv_obj_set_width(ui_Rotate, 30);
    lv_obj_set_height(ui_Rotate, 30);
    lv_obj_set_align(ui_Rotate, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Rotate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Rotate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Rotate);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label1, "Rotate");
    lv_label_set_text_fmt(ui_Label1, LV_SYMBOL_SHUFFLE); 

    // ui_btnCount = lv_btn_create(ui_pnlMain);
    // lv_obj_set_width(ui_btnCount, 80);
    // lv_obj_set_height(ui_btnCount, 30);
    // lv_obj_set_align(ui_btnCount, LV_ALIGN_BOTTOM_RIGHT);
    // lv_obj_add_flag(ui_btnCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_clear_flag(ui_btnCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_lblButton = lv_label_create(ui_btnCount);
    // lv_obj_set_width(ui_lblButton, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_lblButton, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_lblButton, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_lblButton, "Add 1");

    // ui_lblCount = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_lblCount, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_lblCount, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_lblCount, 0);
    // lv_obj_set_y(ui_lblCount, 120);
    // lv_label_set_text(ui_lblCount, "Count:");

    // ui_lblCountValue = lv_label_create(ui_pnlMain);
    // lv_obj_set_width(ui_lblCountValue, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_lblCountValue, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_lblCountValue, 0);
    // lv_obj_set_y(ui_lblCountValue, 120);
    // lv_obj_set_align(ui_lblCountValue, LV_ALIGN_TOP_RIGHT);
    // lv_label_set_text(ui_lblCountValue, "0");

    // ui_Image1 = lv_img_create(ui_pnlMain);
    // lv_img_set_src(ui_Image1, &ui_img_lena80x80_png);
    // lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_RIGHT);
    // lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    // lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Rotate, ui_event_Rotate, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_btnCount, ui_event_btnCount, LV_EVENT_ALL, NULL);

}
